export const SETTINGS_STYLES = `
.sm-page{display:flex;flex-direction:column;gap:20px;max-width:880px;padding:4px 2px 36px;color:var(--dsw-alias-label-primary);font-size:13px}
.sm-hero{display:flex;justify-content:space-between;gap:24px;align-items:center;padding:6px 2px 18px;border-bottom:1px solid var(--dsw-alias-border-l1)}
.sm-brand{display:flex;align-items:center;gap:13px;min-width:0}
.ll-mark{display:grid;place-items:center;width:42px;height:42px;flex:none;border:1px solid color-mix(in srgb,var(--dsw-alias-state-business-primary) 25%,var(--dsw-alias-border-l1));border-radius:14px;background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 8%,transparent);color:var(--dsw-alias-state-business-primary)}
.ll-mark svg{width:30px;height:30px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round}
.sm-title{display:flex;align-items:baseline;gap:8px;margin-bottom:3px}.sm-title h2{margin:0;font-size:21px;letter-spacing:-.025em}.sm-title span{color:var(--dsw-alias-label-secondary);font-size:12px}
.sm-muted{margin:0;color:var(--dsw-alias-label-secondary);line-height:1.55}
.sm-status{display:flex;align-items:center;gap:7px;flex:none;padding:5px 9px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px;color:var(--dsw-alias-label-secondary);font-size:12px}.sm-status i{width:6px;height:6px;border-radius:50%;background:var(--dsw-alias-state-success-primary)}.sm-status[data-state=paused] i{background:var(--dsw-alias-label-secondary)}.sm-status[data-state=off] i{background:var(--dsw-alias-border-l2)}
.sm-metrics{display:flex;align-items:center;gap:0;padding:0 2px}.sm-metric{display:flex;align-items:baseline;gap:5px;padding-right:22px;margin-right:22px;border-right:1px solid var(--dsw-alias-border-l1)}.sm-metric:last-child{border-right:0;margin-right:0;padding-right:0}.sm-metric strong{font-size:17px;font-weight:650;letter-spacing:-.02em}.sm-metric span{color:var(--dsw-alias-label-secondary);font-size:12px}
.sm-nav{display:flex;gap:22px;border-bottom:1px solid var(--dsw-alias-border-l1)}.sm-nav button{position:relative;border:0;padding:0 0 10px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font:inherit}.sm-nav button:after{content:'';position:absolute;right:0;bottom:-1px;left:0;height:2px;border-radius:2px;background:transparent}.sm-nav button[data-active=true]{color:var(--dsw-alias-label-primary);font-weight:600}.sm-nav button[data-active=true]:after{background:var(--dsw-alias-state-business-primary)}
.sm-section{display:flex;flex-direction:column;gap:12px}.sm-section h3{margin:0 0 1px;font-size:14px;font-weight:650}.sm-card{padding:15px 16px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:color-mix(in srgb,var(--dsw-alias-bg-layer-1) 72%,transparent)}
.sm-row{display:flex;align-items:center;justify-content:space-between;gap:20px}.sm-row+.sm-row{margin-top:14px;padding-top:14px;border-top:1px solid var(--dsw-alias-border-l1)}.sm-copy{min-width:0}.sm-copy strong{display:block;margin-bottom:3px;font-weight:600}.sm-inline-tag{display:inline;margin-left:4px;padding:2px 6px;border-radius:999px;background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary);font-size:10px;font-weight:500}
.sm-control{display:flex;align-items:center;gap:8px;flex:none}.sm-control select,.sm-control input[type=number],.sm-search,.sm-textarea{box-sizing:border-box;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:inherit;outline:none}.sm-control select:focus,.sm-control input:focus,.sm-search:focus,.sm-textarea:focus{border-color:var(--dsw-alias-state-business-primary)}.sm-control select,.sm-control input[type=number],.sm-search{height:34px;padding:0 9px}.sm-control input[type=number]{width:110px}.sm-textarea{width:100%;min-height:106px;padding:10px 12px;line-height:1.55;resize:vertical}
.sm-switch{position:relative;width:36px;height:21px;border:0;border-radius:999px;background:var(--dsw-alias-border-l2);cursor:pointer}.sm-switch:after{content:'';position:absolute;top:3px;left:3px;width:15px;height:15px;border-radius:50%;background:white;box-shadow:0 1px 2px #0002;transition:transform .15s}.sm-switch[data-on=true]{background:var(--dsw-alias-state-business-primary)}.sm-switch[data-on=true]:after{transform:translateX(15px)}.sm-switch:disabled{opacity:.45;cursor:default}
.sm-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.sm-btn{height:32px;padding:0 11px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;cursor:pointer}.sm-btn:hover{background:var(--dsw-alias-interactive-bg-hover)}.sm-btn[data-primary=true]{border-color:transparent;background:var(--dsw-alias-button-primary-bg);color:var(--dsw-alias-button-primary-label)}.sm-btn[data-danger=true]{color:var(--dsw-alias-state-error-primary)}.sm-btn:disabled{opacity:.45;cursor:default}
.sm-banner{padding:10px 12px;border-left:2px solid color-mix(in srgb,var(--dsw-alias-state-business-primary) 45%,transparent);border-radius:3px 8px 8px 3px;background:color-mix(in srgb,var(--dsw-specific-tip) 75%,transparent);line-height:1.5}.sm-banner p{margin:5px 0 8px}.sm-error{border-left-color:var(--dsw-alias-state-error-primary);background:color-mix(in srgb,var(--dsw-alias-state-error-primary) 8%,transparent);color:var(--dsw-alias-state-error-primary)}.sm-success{color:var(--dsw-alias-state-success-primary)}
.sm-list{display:flex;flex-direction:column;gap:8px}.sm-rule{padding:12px 13px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px}.sm-rule-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:7px}.sm-tags{display:flex;gap:6px;flex-wrap:wrap}.sm-tag{padding:2px 7px;border-radius:999px;background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary);font-size:11px}.sm-rule p{margin:0;line-height:1.55}.sm-rule-actions{display:flex;gap:4px;margin-top:9px}.sm-rule-actions button{border:0;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font:inherit;padding:3px 6px}.sm-rule-actions button:hover{color:var(--dsw-alias-label-primary)}
.sm-grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.sm-code{margin:0;max-height:360px;overflow:auto;white-space:pre-wrap;padding:14px;border-radius:9px;background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l1);font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.sm-excerpt{max-height:130px;overflow:auto;white-space:pre-wrap;color:var(--dsw-alias-label-secondary);line-height:1.55}.sm-loading{padding:32px;text-align:center;color:var(--dsw-alias-label-secondary)}
@media(max-width:720px){.sm-hero{align-items:flex-start;flex-direction:column}.sm-metrics{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sm-metric,.sm-metric:last-child{margin:0;padding:0;border:0}.sm-nav{gap:16px;overflow-x:auto}.sm-grid2{grid-template-columns:1fr}.sm-row{align-items:flex-start;flex-direction:column}.sm-control{width:100%}}
`

export const DOCK_STYLES = `
.sm-dock{box-sizing:border-box;width:calc(100% - 2 * var(--dsh-composer-side-clearance) - 4 * var(--dsh-composer-dock-inset));margin:0 auto}.sm-dock-bar{box-sizing:border-box;display:flex;align-items:center;gap:8px;width:100%;max-width:calc(var(--dsh-composer-card-max-width) - 4 * var(--dsh-composer-dock-inset));min-height:34px;margin:0 auto;padding:3px 5px 3px 11px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-business-primary) 22%,var(--dsw-alias-border-l1));border-radius:10px;background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 6%,var(--dsw-alias-bg-layer-1));color:var(--dsw-alias-label-primary);font-size:12px}.sm-dock-dot{width:6px;height:6px;border-radius:50%;background:var(--dsw-alias-state-business-primary);flex:none}.sm-dock-title{font-weight:600;flex:none}.sm-dock-detail{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-secondary);flex:1}.sm-dock-btn{width:27px;height:27px;border:0;border-radius:999px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.sm-dock-btn:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.sm-dock-btn:disabled{opacity:.4}
`
